### ISSUE TITLE
error: ISO C90 forbids variable length array

### ISSUE THREAD

**Issue by kenkomu** [Ronnie-Leon76/simple_shell#1]
builtin.c: In function ‘ownCmdHandler’:
builtin.c:9:5: error: ISO C90 forbids variable length array ‘OwnCmds’ [-Werror=vla]
    9 |     char *OwnCmds[NoOfOwnCmds];
      |     ^~~~
cc1: all warnings being treated as errors

and here is my code:
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int ownCmdHandler(char** parsed)
{
    int NoOfOwnCmds = 2, i, switchOwnArg = 0;
    char *OwnCmds[NoOfOwnCmds];

    OwnCmds[0] = "exit";
    OwnCmds[1] = "cd";

    for (i = 0; i < NoOfOwnCmds; i++) {
        if (strcmp(parsed[0], OwnCmds[i]) == 0) {
            switchOwnArg = i + 1;
            break;
        }
    }

    switch (switchOwnArg) {
        case 1:
            printf("\nGoodbye\n");
            exit(0);
        case 2:
            chdir(parsed[1]);
            return 1;
        default:
            break;
    }

    return 0;
}

**Comment by Ronnie-Leon76** [comment]
File removed!
